export interface PickupHub {
  id: string;
  name: string;
  city: string;
  district: string;
  area: string;
  landmark: string;
  fullAddress: string;
  lat: number;
  lng: number;
  operatingHours: string;
  managerPhone: string;
  managerName: string;
  googleMapsUrl: string;
  featured: boolean;
  amenities: string[];
  stationedCarsCount: number;
}

export const OFFICIAL_PICKUP_HUBS: PickupHub[] = [
  // 1. Proddatur Hubs
  {
    id: "hub-prd-01",
    name: "Proddatur RTC Bus Stand Hub",
    city: "Proddatur",
    district: "YSR Kadapa",
    area: "Korrapadu Road",
    landmark: "Near New RTC Bus Stand Entrance",
    fullAddress: "Korrapadu Road, Near RTC Central Bus Station, Proddatur, Andhra Pradesh 516360",
    lat: 14.7505,
    lng: 78.5521,
    operatingHours: "24 Hours / 7 Days",
    managerPhone: "+917893817322",
    managerName: "Ramesh Reddy",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Proddatur+RTC+Bus+Stand+Andhra+Pradesh",
    featured: true,
    amenities: ["24/7 Handover", "Sanitization Station", "Free 2-Wheeler Parking", "Instant KYC Verification"],
    stationedCarsCount: 6,
  },
  {
    id: "hub-prd-02",
    name: "Gandhi Road Clock Tower Center",
    city: "Proddatur",
    district: "YSR Kadapa",
    area: "Gandhi Road",
    landmark: "Opposite Clock Tower & Gold Market",
    fullAddress: "Main Gandhi Road, Clock Tower Circle, Proddatur, Andhra Pradesh 516360",
    lat: 14.7523,
    lng: 78.5539,
    operatingHours: "6:00 AM - 11:00 PM",
    managerPhone: "+917893817322",
    managerName: "Siva Kumar Naidu",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Clock+Tower+Gandhi+Road+Proddatur",
    featured: true,
    amenities: ["Central Location", "Doorstep Dispatch", "EV Charging Point"],
    stationedCarsCount: 4,
  },
  {
    id: "hub-prd-03",
    name: "Mydukur Road Station",
    city: "Proddatur",
    district: "YSR Kadapa",
    area: "Mydukur Road",
    landmark: "Near Reliance Smart Bazaar & HP Petrol Pump",
    fullAddress: "Mydukur Highway Road, Proddatur, Andhra Pradesh 516360",
    lat: 14.7480,
    lng: 78.5610,
    operatingHours: "24 Hours",
    managerPhone: "+917893817322",
    managerName: "Ramesh Reddy",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Reliance+Smart+Bazaar+Mydukur+Road+Proddatur",
    featured: false,
    amenities: ["Highway Handover", "Fuel Station Adjacent", "Fast Handover"],
    stationedCarsCount: 3,
  },
  {
    id: "hub-prd-04",
    name: "Holmespet Temple Point",
    city: "Proddatur",
    district: "YSR Kadapa",
    area: "Holmespet",
    landmark: "Near Sri Vasavi Kanyaka Parameswari Temple",
    fullAddress: "Holmespet Main Road, Proddatur, Andhra Pradesh 516360",
    lat: 14.7550,
    lng: 78.5490,
    operatingHours: "7:00 AM - 10:00 PM",
    managerPhone: "+917893817322",
    managerName: "Siva Kumar",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Holmespet+Proddatur+Andhra+Pradesh",
    featured: false,
    amenities: ["Residential Handover", "Sanitized Cars"],
    stationedCarsCount: 2,
  },
  {
    id: "hub-prd-05",
    name: "Bollavaram YMR Colony Hub",
    city: "Proddatur",
    district: "YSR Kadapa",
    area: "Bollavaram",
    landmark: "Near YMR Colony Entrance Arch",
    fullAddress: "YMR Colony Main Road, Bollavaram, Proddatur, Andhra Pradesh 516360",
    lat: 14.7420,
    lng: 78.5440,
    operatingHours: "6:00 AM - 10:00 PM",
    managerPhone: "+917893817322",
    managerName: "Ramesh Reddy",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=YMR+Colony+Bollavaram+Proddatur",
    featured: false,
    amenities: ["Parking Available", "Family Car Delivery"],
    stationedCarsCount: 3,
  },

  // 2. Kadapa Hubs
  {
    id: "hub-kdp-01",
    name: "Kadapa RTC Central Complex Hub",
    city: "Kadapa",
    district: "YSR District",
    area: "Seven Roads Circle",
    landmark: "Opposite Main RTC Complex Gate 1",
    fullAddress: "Seven Roads Circle, Near RTC Central Complex, Kadapa, Andhra Pradesh 516001",
    lat: 14.4735,
    lng: 78.8260,
    operatingHours: "24 Hours / 7 Days",
    managerPhone: "+917893817322",
    managerName: "Kadapa Hub Team",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Kadapa+RTC+Bus+Stand+Seven+Roads",
    featured: true,
    amenities: ["24/7 Handover", "Airport/Station Shuttle", "Luggage Assistance"],
    stationedCarsCount: 5,
  },
  {
    id: "hub-kdp-02",
    name: "Kadapa Railway Station Point",
    city: "Kadapa",
    district: "YSR District",
    area: "Railway Station Road",
    landmark: "Platform 1 Main Exit Parking",
    fullAddress: "Kadapa Railway Station Road, Nagarajupalli, Kadapa, Andhra Pradesh 516001",
    lat: 14.4840,
    lng: 78.8190,
    operatingHours: "24 Hours",
    managerPhone: "+917893817322",
    managerName: "Kadapa Hub Team",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Kadapa+Railway+Station+Andhra+Pradesh",
    featured: true,
    amenities: ["Train Arrival Handover", "Instant Verification", "Clean Cars"],
    stationedCarsCount: 4,
  },

  // 3. Tirupati Hubs
  {
    id: "hub-tpt-01",
    name: "Renigunta Airport Terminal Hub",
    city: "Tirupati",
    district: "Tirupati District",
    area: "Renigunta",
    landmark: "Arrivals Terminal Dedicated Parking",
    fullAddress: "Tirupati International Airport, Renigunta, Andhra Pradesh 517520",
    lat: 13.6320,
    lng: 79.5430,
    operatingHours: "24 Hours",
    managerPhone: "+917893817322",
    managerName: "Tirupati Hub Team",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Tirupati+International+Airport+Renigunta",
    featured: true,
    amenities: ["Flight Tracking Handover", "Chauffeur Ready", "Tirumala Ghat Road Permitted"],
    stationedCarsCount: 5,
  },
  {
    id: "hub-tpt-02",
    name: "Alipiri Toll Gate Hub",
    city: "Tirupati",
    district: "Tirupati District",
    area: "Alipiri",
    landmark: "Foot of Tirumala Hills Toll Plaza",
    fullAddress: "Alipiri Bypass Road, Tirupati, Andhra Pradesh 517507",
    lat: 13.6550,
    lng: 79.4010,
    operatingHours: "24 Hours",
    managerPhone: "+917893817322",
    managerName: "Tirupati Hub Team",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Alipiri+Toll+Gate+Tirupati",
    featured: false,
    amenities: ["Ghat Road Certified Cars", "Fastag Enabled", "24/7 Security"],
    stationedCarsCount: 3,
  },

  // 4. Jammalamadugu (Gandikota Hub)
  {
    id: "hub-jmd-01",
    name: "Gandikota Fort Highway Point",
    city: "Jammalamadugu",
    district: "YSR Kadapa",
    area: "Gandikota Road",
    landmark: "Near Jammalamadugu RTC Bus Stand & Fort Road Junction",
    fullAddress: "Gandikota Highway Road, Jammalamadugu, Andhra Pradesh 516434",
    lat: 14.8380,
    lng: 78.3910,
    operatingHours: "6:00 AM - 10:00 PM",
    managerPhone: "+917893817322",
    managerName: "Jammalamadugu Coordinator",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Jammalamadugu+RTC+Bus+Stand",
    featured: true,
    amenities: ["Grand Canyon Quick Access", "SUV Off-road Ready", "Sunset Trip Specialist"],
    stationedCarsCount: 3,
  },

  // 5. Mydukur Hub
  {
    id: "hub-myd-01",
    name: "Four Roads Junction Hub",
    city: "Mydukur",
    district: "YSR Kadapa",
    area: "Four Roads Circle",
    landmark: "NH 40 & NH 67 Highway Junction",
    fullAddress: "Four Roads Circle, Mydukur, Andhra Pradesh 516172",
    lat: 14.7080,
    lng: 78.7180,
    operatingHours: "24 Hours",
    managerPhone: "+917893817322",
    managerName: "Mydukur Coordinator",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mydukur+Four+Roads+Junction",
    featured: false,
    amenities: ["Interstate Junction Handover", "Fast Roadside Delivery"],
    stationedCarsCount: 2,
  },

  // 6. Pulivendula Hub
  {
    id: "hub-pul-01",
    name: "Pulivendula RTC Complex Hub",
    city: "Pulivendula",
    district: "YSR Kadapa",
    area: "Main Bus Station",
    landmark: "Near YSR Circle & RIMS Pulivendula",
    fullAddress: "RTC Bus Stand Road, Pulivendula, Andhra Pradesh 516390",
    lat: 14.4230,
    lng: 78.2310,
    operatingHours: "6:00 AM - 10:00 PM",
    managerPhone: "+917893817322",
    managerName: "Pulivendula Team",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Pulivendula+RTC+Bus+Stand",
    featured: false,
    amenities: ["Doorstep Delivery Available", "Fully Sanitized"],
    stationedCarsCount: 2,
  },
];
