import { Car, Booking, Location, Profile, OwnerProfile, Review } from '@/types';
import { PRODDATUR_LOCATIONS } from '@/lib/constants';

export const INITIAL_LOCATIONS: Location[] = [...PRODDATUR_LOCATIONS];

export const INITIAL_OWNERS: (Profile & { owner_profile: OwnerProfile })[] = [
  {
    id: "usr-owner-1",
    email: "ramesh.cars@gmail.com",
    full_name: "Ramesh Reddy",
    phone: "+91 98490 12345",
    role: "owner",
    status: "active",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    created_at: "2026-01-15T10:00:00.000Z",
    updated_at: "2026-01-15T10:00:00.000Z",
    owner_profile: {
      id: "usr-owner-1",
      kyc_status: "approved",
      address_line1: "D.No 4/281, Korrapadu Road",
      city: "Proddatur",
      state: "Andhra Pradesh",
      pincode: "516360",
      aadhar_masked: "XXXX-XXXX-8921",
      driving_license_no: "AP0420180019234",
      bank_account_name: "Ramesh Reddy Cars",
      bank_account_number: "91802003891234",
      bank_ifsc: "SBIN0000902",
      bank_name: "State Bank of India - Proddatur Main",
      upi_id: "rameshcars@sbi",
      verified_at: "2026-01-16T14:30:00.000Z"
    }
  },
  {
    id: "usr-owner-2",
    email: "siva.rentals@gmail.com",
    full_name: "Siva Kumar Naidu",
    phone: "+91 94401 56789",
    role: "owner",
    status: "active",
    avatar_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    created_at: "2026-02-01T09:00:00.000Z",
    updated_at: "2026-02-01T09:00:00.000Z",
    owner_profile: {
      id: "usr-owner-2",
      kyc_status: "approved",
      address_line1: "Near Clock Tower, Gandhi Road",
      city: "Proddatur",
      state: "Andhra Pradesh",
      pincode: "516360",
      aadhar_masked: "XXXX-XXXX-4512",
      driving_license_no: "AP0420190088129",
      bank_account_name: "Siva Kumar Naidu",
      bank_account_number: "50100239102934",
      bank_ifsc: "HDFC0001089",
      bank_name: "HDFC Bank Proddatur",
      upi_id: "sivarentals@hdfcbank",
      verified_at: "2026-02-02T11:00:00.000Z"
    }
  },
  {
    id: "usr-owner-3",
    email: "venkat.selfdrive@gmail.com",
    full_name: "Venkata Krishna",
    phone: "+91 99887 76655",
    role: "owner",
    status: "pending_verification",
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    created_at: "2026-08-25T11:20:00.000Z",
    updated_at: "2026-08-25T11:20:00.000Z",
    owner_profile: {
      id: "usr-owner-3",
      kyc_status: "pending_verification",
      address_line1: "Mydukur Road, Beside HP Petrol Bunk",
      city: "Proddatur",
      state: "Andhra Pradesh",
      pincode: "516360",
      aadhar_masked: "XXXX-XXXX-7721",
      driving_license_no: "AP0420210045123",
      bank_account_name: "Venkata Krishna",
      bank_account_number: "30291029384910",
      bank_ifsc: "ICIC0000892",
      bank_name: "ICICI Bank Proddatur",
      upi_id: "venkatdrive@icici"
    }
  }
];

export const INITIAL_CARS: Car[] = [
  {
    id: "car-prd-01",
    owner_id: "usr-owner-1",
    location_id: "loc-prd-1",
    brand: "Maruti Suzuki",
    model: "Swift",
    variant: "ZXi Plus",
    year: 2023,
    registration_number: "AP 04 CK 1248",
    fuel_type: "petrol",
    transmission: "manual",
    category: "hatchback",
    seating_capacity: 5,
    color: "Pearl Arctic White",
    kilometer_reading: 24500,
    mileage_kmpl: 22.5,
    price_per_day: 1800,
    price_per_hour: 120,
    security_deposit: 2000,
    min_rental_hours: 12,
    max_rental_days: 30,
    delivery_available: true,
    delivery_charges: 250,
    description: "Well-maintained, smooth and fuel-efficient Maruti Swift ZXi+. Perfect for city rides, Kadapa trips, and weekend getaways from Proddatur. Equipped with Android Auto and chilling AC.",
    features: ["Bluetooth Audio", "Touchscreen Infotainment", "Reverse Parking Camera", "Dual Airbags", "Chilling AC", "Steering Mounted Controls", "ABS with EBD"],
    approval_status: "approved",
    slug: "maruti-swift-zxi-proddatur-01",
    images: [
      { id: "img-1", image_url: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=900&auto=format&fit=crop&q=80", is_primary: true },
      { id: "img-2", image_url: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=900&auto=format&fit=crop&q=80", is_primary: false },
      { id: "img-3", image_url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=900&auto=format&fit=crop&q=80", is_primary: false }
    ],
    rating: 4.9,
    total_reviews: 28,
    created_at: "2026-01-20T10:00:00.000Z"
  },
  {
    id: "car-prd-02",
    owner_id: "usr-owner-1",
    location_id: "loc-prd-1",
    brand: "Hyundai",
    model: "Creta",
    variant: "SX (O) Turbo",
    year: 2024,
    registration_number: "AP 04 EQ 7788",
    fuel_type: "petrol",
    transmission: "automatic",
    category: "suv",
    seating_capacity: 5,
    color: "Abyss Black",
    kilometer_reading: 14200,
    mileage_kmpl: 17.0,
    price_per_day: 3200,
    price_per_hour: 220,
    security_deposit: 3000,
    min_rental_hours: 12,
    max_rental_days: 30,
    delivery_available: true,
    delivery_charges: 300,
    description: "Top-end Hyundai Creta Automatic with Panoramic Sunroof, Bose Sound System, Ventilated Seats, and ADAS Level 2. Luxury driving experience for VIP guests and long highway drives.",
    features: ["Panoramic Sunroof", "Automatic Transmission", "Bose Premium Audio", "Ventilated Front Seats", "Wireless Charging", "ADAS Level 2", "360-Degree Camera", "Leatherette Upholstery"],
    approval_status: "approved",
    slug: "hyundai-creta-sx-automatic-proddatur-02",
    images: [
      { id: "img-4", image_url: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=900&auto=format&fit=crop&q=80", is_primary: true },
      { id: "img-5", image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=900&auto=format&fit=crop&q=80", is_primary: false }
    ],
    rating: 5.0,
    total_reviews: 19,
    created_at: "2026-02-10T11:00:00.000Z"
  },
  {
    id: "car-prd-03",
    owner_id: "usr-owner-2",
    location_id: "loc-prd-2",
    brand: "Toyota",
    model: "Innova Crysta",
    variant: "2.4 VX 7-Seater",
    year: 2023,
    registration_number: "AP 04 DL 9900",
    fuel_type: "diesel",
    transmission: "manual",
    category: "seven_seater",
    seating_capacity: 7,
    color: "Silver Metallic",
    kilometer_reading: 38000,
    mileage_kmpl: 15.2,
    price_per_day: 3800,
    price_per_hour: 250,
    security_deposit: 3500,
    min_rental_hours: 24,
    max_rental_days: 30,
    delivery_available: true,
    delivery_charges: 350,
    description: "The King of highway comfort! 7-seater Toyota Innova Crysta Diesel with captain seats in middle row. Ideal for family pilgrimages to Tirupati, Ahobilam, Mahanandi or Bangalore airport trips.",
    features: ["7-Seater Captain Seats", "Rear AC Vents for all 3 Rows", "Touchscreen Navigation", "Push Button Start", "Cruise Control", "Large Boot Space", "Roof Ambient Lighting"],
    approval_status: "approved",
    slug: "toyota-innova-crysta-7-seater-proddatur-03",
    images: [
      { id: "img-6", image_url: "https://images.unsplash.com/photo-1590362891988-f77804702e0a?w=900&auto=format&fit=crop&q=80", is_primary: true },
      { id: "img-7", image_url: "https://images.unsplash.com/photo-1502877338535-766e1452684a?w=900&auto=format&fit=crop&q=80", is_primary: false }
    ],
    rating: 4.8,
    total_reviews: 42,
    created_at: "2026-02-15T12:00:00.000Z"
  },
  {
    id: "car-prd-04",
    owner_id: "usr-owner-2",
    location_id: "loc-prd-3",
    brand: "Tata Motors",
    model: "Nexon",
    variant: "XZ+ (S) Diesel",
    year: 2023,
    registration_number: "AP 04 BM 3344",
    fuel_type: "diesel",
    transmission: "manual",
    category: "suv",
    seating_capacity: 5,
    color: "Daytona Grey",
    kilometer_reading: 29000,
    mileage_kmpl: 21.0,
    price_per_day: 2300,
    price_per_hour: 150,
    security_deposit: 2500,
    min_rental_hours: 12,
    max_rental_days: 30,
    delivery_available: true,
    delivery_charges: 200,
    description: "5-Star Global NCAP safety certified compact SUV. High ground clearance, strong punchy diesel engine with Eco/City/Sport drive modes. Electric Sunroof included.",
    features: ["5-Star Safety Rating", "Electric Sunroof", "Drive Modes (Eco, City, Sport)", "Harman Audio System", "Rear AC Vents", "Digital Instrument Cluster"],
    approval_status: "approved",
    slug: "tata-nexon-xz-plus-diesel-proddatur-04",
    images: [
      { id: "img-8", image_url: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=900&auto=format&fit=crop&q=80", is_primary: true }
    ],
    rating: 4.9,
    total_reviews: 15,
    created_at: "2026-03-01T10:00:00.000Z"
  },
  {
    id: "car-prd-05",
    owner_id: "usr-owner-1",
    location_id: "loc-prd-4",
    brand: "Mahindra",
    model: "Thar 4x4",
    variant: "LX Hard Top Diesel",
    year: 2024,
    registration_number: "AP 04 GH 5555",
    fuel_type: "diesel",
    transmission: "automatic",
    category: "suv",
    seating_capacity: 4,
    color: "Red Rage",
    kilometer_reading: 11000,
    mileage_kmpl: 14.5,
    price_per_day: 3500,
    price_per_hour: 240,
    security_deposit: 4000,
    min_rental_hours: 24,
    max_rental_days: 15,
    delivery_available: false,
    delivery_charges: 0,
    description: "Authentic 4x4 Off-roader lifestyle vehicle! Mahindra Thar Automatic Hard Top with 4WD, Touchscreen display, roll cage, and iconic commanding road presence.",
    features: ["4x4 Four Wheel Drive", "Automatic Transmission", "Hard Top", "Touchscreen Display", "All-Terrain Tyres", "Adventure Statistics"],
    approval_status: "approved",
    slug: "mahindra-thar-4x4-automatic-proddatur-05",
    images: [
      { id: "img-9", image_url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=900&auto=format&fit=crop&q=80", is_primary: true }
    ],
    rating: 5.0,
    total_reviews: 22,
    created_at: "2026-03-10T14:00:00.000Z"
  },
  {
    id: "car-prd-06",
    owner_id: "usr-owner-3",
    location_id: "loc-prd-3",
    brand: "Maruti Suzuki",
    model: "Ertiga",
    variant: "ZXi CNG",
    year: 2024,
    registration_number: "AP 04 JK 8812",
    fuel_type: "cng",
    transmission: "manual",
    category: "seven_seater",
    seating_capacity: 7,
    color: "Magma Grey",
    kilometer_reading: 16500,
    mileage_kmpl: 26.0,
    price_per_day: 2500,
    price_per_hour: 170,
    security_deposit: 2500,
    min_rental_hours: 12,
    max_rental_days: 30,
    delivery_available: true,
    delivery_charges: 200,
    description: "Most economical 7-seater MPV with Factory Fitted S-CNG. Huge fuel savings for outstation group trips, wedding guest transportation and temple visits.",
    features: ["Factory Fitted S-CNG", "7-Seater Practicality", "SmartPlay Pro Infotainment", "Rear AC Vents", "Keyless Entry & Push Start"],
    approval_status: "pending_approval",
    slug: "maruti-ertiga-zxi-cng-proddatur-06",
    images: [
      { id: "img-10", image_url: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=900&auto=format&fit=crop&q=80", is_primary: true }
    ],
    rating: 0,
    total_reviews: 0,
    created_at: "2026-08-26T16:00:00.000Z"
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: "rev-1",
    booking_id: "bk-prd-01",
    car_id: "car-prd-01",
    customer_id: "usr-cust-1",
    owner_id: "usr-owner-1",
    rating: 5,
    comment: "Rented the Swift for a 2-day trip to Kadapa and Gandikota. Car was squeaky clean, AC was powerful, and Ramesh garu handed over the keys right on time at Proddatur RTC bus stand. Highly recommended!",
    created_at: "2026-08-10T16:30:00.000Z",
    customer: { full_name: "Pavan Kalyan M", avatar_url: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80" }
  },
  {
    id: "rev-2",
    booking_id: "bk-prd-02",
    car_id: "car-prd-02",
    customer_id: "usr-cust-2",
    owner_id: "usr-owner-1",
    rating: 5,
    comment: "The Creta Automatic is fantastic. Traveled to Bangalore with family. Smooth gearbox, very comfortable for parents. Security deposit was refunded within 6 hours of return!",
    created_at: "2026-08-18T18:00:00.000Z",
    customer: { full_name: "Dr. Lakshmi Prasad", avatar_url: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80" }
  },
  {
    id: "rev-3",
    booking_id: "bk-prd-03",
    car_id: "car-prd-03",
    customer_id: "usr-cust-3",
    owner_id: "usr-owner-2",
    rating: 5,
    comment: "Booked Innova Crysta for Tirupati darshan with 6 family members. Ample legroom, spotless interiors. Siva Kumar was very polite and helpful.",
    created_at: "2026-08-22T20:15:00.000Z",
    customer: { full_name: "Subba Rao V", avatar_url: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&auto=format&fit=crop&q=80" }
  }
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: "bk-prd-01",
    booking_reference: "PRD-2026-000101",
    customer_id: "usr-cust-1",
    owner_id: "usr-owner-1",
    car_id: "car-prd-01",
    pickup_location_id: "loc-prd-1",
    start_time: "2026-09-02T10:00:00.000Z",
    end_time: "2026-09-04T10:00:00.000Z",
    duration_hours: 48,
    rental_type: "self_drive",
    delivery_requested: false,
    base_rental_amount: 3600,
    delivery_amount: 0,
    taxes_fees_amount: 180,
    security_deposit_amount: 2000,
    total_amount: 5780,
    platform_commission_rate: 10,
    platform_commission_amount: 360,
    owner_earnings_amount: 3240,
    status: "confirmed",
    created_at: "2026-08-28T09:30:00.000Z",
    car: INITIAL_CARS[0],
    customer: {
      id: "usr-cust-1",
      email: "pavan.kalyan@gmail.com",
      full_name: "Pavan Kalyan M",
      phone: "+91 91234 56780",
      role: "customer",
      status: "active",
      created_at: "2026-01-10T00:00:00Z",
      updated_at: "2026-01-10T00:00:00Z"
    },
    pickup_location: INITIAL_LOCATIONS[0],
    payment: {
      id: "pay-101",
      order_id: "order_PRD_2026_000101_cf",
      status: "successful",
      payment_method: "UPI"
    }
  }
];
